apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
    tier: caching
    appMajor: "5"
    uri: dev-drupal.redis.lib.unb.ca
  name: drupal-redis-lib-unb-ca
  namespace: dev
spec:
  selector:
    matchLabels:
      uri: dev-drupal.redis.lib.unb.ca
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: redis
        tier: caching
        appMajor: "5"
        uri: dev-drupal.redis.lib.unb.ca
    spec:
      nodeSelector:
        deployenv: dev
      containers:
        -
          name: drupal-redis-lib-unb-ca
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
          env:
            -
              name: REDIS_HOME
              value: "/data"
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          ports:
            -
              containerPort: 6379
              name: redis
      imagePullSecrets:
        -
          name: docker-hub-auth
      priorityClassName: dev-high-priority-services
      restartPolicy: Always
